### ISSUE TITLE
Displaying more descriptive study scenario names

### ISSUE THREAD

**Issue by heidimok** [Dashboard-IN3/tecnico-energy-app#43]
## Context

Currently the application displays the values of each scenario such as `E1 Scenario,` `B2 Scenario_1 `on the UI which are short and easy to understand from a data/csv perspective but not easy to understand as a user selecting between scenarios. 

Left image: Municipal study scenarios
Right image: Buildings study scenarios
<img width="154" alt="image" src="https://github.com/developmentseed/tecnico-energy-app/assets/10764915/9446628a-a4d1-4453-97be-f4cbcd870239">
<img width="203" alt="image" src="https://github.com/developmentseed/tecnico-energy-app/assets/10764915/26e6e29b-ae3d-49c5-a588-20fcadcf7aa6">

## Ideal
A way to provide descriptive, yet concise names for scenarios and selections on the UI in a way that also makes sense on the data/csv side.

**Comment by heidimok** [comment]
This is an additional concept that was inspired by https://explorer.audubon.org/home?legend=collapse&layersPanel=expand

<img width="210" alt="image" src="https://github.com/developmentseed/tecnico-energy-app/assets/10764915/37ff831a-7c69-426d-a761-032221daaa4a">
 
It allows users to toggle on descriptions in the legend and places the text in context of the label.

**Comment by alukach** [comment]
<img width="294" alt="image" src="https://github.com/user-attachments/assets/3fee2797-6c8c-4c81-a7ca-157d86fd8c8b">
A description is now supported.
